### ISSUE TITLE
Transaction hash of signed transaction hex

### ISSUE THREAD

**Issue by fredrikblau** [monero-ecosystem/monero-ts#152]
How do I obtain the transaction ID of a signed transaction hex after using the `signTxs` method? When using the [sign_transfer](https://www.getmonero.org/resources/developer-guides/wallet-rpc.html#sign_transfer) method in `monero-wallet-rpc`, it provides the hash after the signing process. How can I achieve the same result?

**Comment by woodser** [comment]
It appears the library's API needs updated to return `MoneroTxSet` instead of `string`. I can include this change in the next release.

**Comment by woodser** [comment]
This is fixed now in the 0.9.4 release by returning `MoneroTxSet`. Thanks for pointing this out.
