### ISSUE TITLE
npm package version outdated

### ISSUE THREAD

**Issue by amirmovafagh** [monero-ecosystem/monero-ts#159]
Hi
the last version of monero-javascript is 0.8.4 in npmjs
please fix this

**Comment by woodser** [comment]
Hello, the project was renamed from monero-javascript to monero-ts. npmjs has the latest version, 0.9.4, under the new project name: https://www.npmjs.com/package/monero-ts.

**Comment by woodser** [comment]
I marked the old monero-javascript repository as deprecated on npmjs. Thanks for pointing this out.
