### ISSUE TITLE
Support typescript

### ISSUE THREAD

**Issue by woodser** [monero-ecosystem/monero-ts#81]
This issue requests supporting typescript.

**Comment by hundehausen** [comment]
Hello @woodser how is it doing with TypeScript support? We at TipXMR could really make use of the types.

**Comment by woodser** [comment]
This PR in progress is successfully generating types and using them in typescript tests: https://github.com/monero-ecosystem/monero-javascript/pull/108

Remaining work is to add jsdocs throughout the models to generate all type information.

The PR also switches from `require()` to `import()` syntax, so it'll be bigger breaking change.

I'd like to close it out but the issue is finding time to finalize everything. There's still quite a bit left to do if anyone can continue developing the PR.

`npm run emit_typedefs_linux.sh` or `npm run emit_typedefs_mac.sh` generates the typedefs and then `npm run test -- --grep "Sample code demonstration"` will run a test with the types.

**Comment by plowsof** [comment]
a bounty for this to be completed has been set up https://bounties.monero.social/posts/80 (currently at 2 xmr)

**Comment by woodser** [comment]
This issue is completed with #108 and released in monero-ts v0.9.2.
